"""Generate the Windows version resource for the frozen executable.

The strings come from ``pixelpack`` itself -- the same constants the About
dialog displays -- so the EXE's Properties page and the About box cannot
disagree, and neither has a second copy to update.

    python scripts/make_version_info.py

The file is written as pure ASCII (non-ASCII characters are emitted as
escapes), because PyInstaller reads it with an encoding this script should not
have to guess at.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

# A Chinese Windows console is GBK and cannot encode the "©" in COPYRIGHT.
# Backslash-escaping the odd character keeps the rest of the report readable
# and, more importantly, keeps the output decodable by the caller.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(errors="backslashreplace")

from pixelpack import (  # noqa: E402
    APP_NAME,
    COMPANY,
    COPYRIGHT,
    DESCRIPTION,
    VERSION,
)

OUT_PATH = ROOT / "assets" / "version_info.txt"

#: Chinese (Simplified) + Unicode. The string table key is these two values
#: concatenated, which is how the resource format identifies it.
LANGUAGE_ID = 0x0804
CODEPAGE = 1200


def version_tuple(text: str) -> tuple[int, int, int, int]:
    """``"1.2.3"`` -> ``(1, 2, 3, 0)``; Windows wants exactly four numbers."""
    parts: list[int] = []
    for chunk in text.split(".")[:4]:
        digits = "".join(character for character in chunk if character.isdigit())
        parts.append(int(digits) if digits else 0)
    while len(parts) < 4:
        parts.append(0)
    return parts[0], parts[1], parts[2], parts[3]


def literal(value: str) -> str:
    """A Python string literal containing ASCII only."""
    return ascii(value)


def build() -> str:
    file_version = version_tuple(VERSION)
    numbers = ", ".join(str(part) for part in file_version)

    fields = [
        ("CompanyName", COMPANY),
        ("FileDescription", DESCRIPTION),
        ("FileVersion", VERSION),
        ("InternalName", APP_NAME),
        ("LegalCopyright", COPYRIGHT),
        ("OriginalFilename", f"{APP_NAME}.exe"),
        ("ProductName", APP_NAME),
        ("ProductVersion", VERSION),
    ]
    structs = ",\n".join(
        f"            StringStruct({literal(name)}, {literal(value)})"
        for name, value in fields
    )

    return f"""\
# Generated by scripts/make_version_info.py from the pixelpack package
# constants. Do not edit by hand; edit src/pixelpack/__init__.py and rebuild.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({numbers}),
    prodvers=({numbers}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        {literal(f"{LANGUAGE_ID:04x}{CODEPAGE:04x}")},
        [
{structs}
        ])
    ]),
    VarFileInfo([VarStruct({literal('Translation')}, [{LANGUAGE_ID}, {CODEPAGE}])])
  ]
)
"""


def main() -> int:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(build(), encoding="ascii", newline="\n")
    print(f"已生成 {OUT_PATH}")
    print(f"  CompanyName    {COMPANY}")
    print(f"  FileVersion    {VERSION}")
    print(f"  LegalCopyright {COPYRIGHT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
